version: "3"
services:
  website:
    build: ./website
    depends_on:
      - projectinfo-service
    ports:
      - "${WEBSITE_PORT}:80"
    volumes:
      - ${WEBSITE_CV_FILES}:/var/www/files
      - web-root:/var/www/html
      - .config/nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
    restart: unless-stopped

  projectinfo-service:
    build: ./projectinfo
    ports:
      - ${PROJECTINFO_PORT}:80
    volumes:
      - ${PROJECTINFO_CONFIG_VOLUME}
    environment:
      - PROJECTINFO_CONFIG_FILE=${PROJECTINFO_CONFIG_FILE}

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - website
    command: certonly --webroot --webroot-path=/var/www/html --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --staging -d ${CERTBOT_DOMAIN}  -d www.${CERTBOT_DOMAIN}