version: "3"
services:
  website:
    build: ./website
    depends_on:
      - projectinfo-service
    ports:
      - "${WEBSITE_PORT}:80"
    volumes:
      - ${WEBSITE_CV_FILES}:/etc/files
  projectinfo-service:
    build: ./projectinfo
    ports:
      - ${PROJECTINFO_PORT}:80
    volumes:
      - ${PROJECTINFO_CONFIG_VOLUME}
    environment:
      - PROJECTINFO_CONFIG_FILE=${PROJECTINFO_CONFIG_FILE}