version: "3"
services:
  website:
    build: ./website
    depends_on:
      - projectinfo-service
    ports:
      - "${WEBSITE_PORT}:80"
    volumes:
      - ${WEBSITE_CV_FILES}:/var/www/files
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  projectinfo-service:
    build: ./projectinfo
    ports:
      # Untoggle this if using in non-TLS mode
      #- ${PROJECTINFO_PORT}:80
      - ${PROJECTINFO_PORT}:443
    volumes:
      - ${PROJECTINFO_CONFIG_VOLUME}
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - PROJECTINFO_CONFIG_FILE=${PROJECTINFO_CONFIG_FILE}
